"""Public market-data API."""

from quantbot.market_data.alpaca import AlpacaMarketDataClient
from quantbot.market_data.base import (
    AdjustmentMode,
    AsyncMarketDataTransport,
    BarQuery,
    BarSource,
    HistoricalMarketDataClient,
    MarketDataBatch,
    MarketDataError,
    MarketDataFeed,
    MarketDataProtocolError,
    MarketDataRequestError,
    MarketDataTransportError,
    MarketSessionClose,
    Sleeper,
    TransportResponse,
)
from quantbot.market_data.cache import MarketDataCache
from quantbot.market_data.calendar import (
    ALPACA_PAPER_CALENDAR_URL,
    AlpacaMarketCalendar,
    latest_completed_session,
    session_closes,
    session_sequence,
)
from quantbot.market_data.crypto import (
    ALPACA_CRYPTO_BARS_URL,
    CRYPTO_ADJUSTMENT,
    AlpacaCryptoDataClient,
)
from quantbot.market_data.fred import (
    KNOWN_SERIES,
    FredError,
    FredProvider,
    FredTransport,
    MacroSeries,
    RevisionUnavailable,
    period_end,
)
from quantbot.market_data.instruments import (
    AssetClass,
    CorporateAction,
    CorporateActionKind,
    Instrument,
    InstrumentUniverse,
    universe_from,
)
from quantbot.market_data.pointintime import (
    Availability,
    Capability,
    FeatureSpec,
    Observation,
    PointInTimeViolation,
    ResearchDataProvider,
    UnsupportedCapability,
    Vintage,
    knowable,
    latest_knowable,
    require,
    session_availability,
)
from quantbot.market_data.stream import (
    AlpacaStockDataStream,
    StreamDisconnected,
    StreamError,
    StreamProtocolError,
    StreamStaleError,
    WebSocketConnection,
    WebSocketConnector,
)
from quantbot.market_data.transports import (
    HttpxMarketDataTransport,
    WebsocketsConnection,
    WebsocketsConnector,
)
from quantbot.market_data.validation import (
    BarValidationReport,
    DataGap,
    DataGapReason,
    MarketDataValidationError,
    align_daily_bars_to_session_closes,
    implausible_range,
    validate_bar_batch,
)

__all__ = [
    "KNOWN_SERIES",
    "FredError",
    "FredProvider",
    "FredTransport",
    "MacroSeries",
    "RevisionUnavailable",
    "period_end",
    "AssetClass",
    "Availability",
    "Capability",
    "CorporateAction",
    "CorporateActionKind",
    "FeatureSpec",
    "Instrument",
    "InstrumentUniverse",
    "Observation",
    "PointInTimeViolation",
    "ResearchDataProvider",
    "UnsupportedCapability",
    "Vintage",
    "knowable",
    "latest_knowable",
    "require",
    "session_availability",
    "universe_from",
    "ALPACA_PAPER_CALENDAR_URL",
    "ALPACA_CRYPTO_BARS_URL",
    "AdjustmentMode",
    "AlpacaCryptoDataClient",
    "AlpacaMarketCalendar",
    "AlpacaMarketDataClient",
    "AlpacaStockDataStream",
    "AsyncMarketDataTransport",
    "CRYPTO_ADJUSTMENT",
    "BarQuery",
    "BarSource",
    "BarValidationReport",
    "DataGap",
    "DataGapReason",
    "implausible_range",
    "HistoricalMarketDataClient",
    "HttpxMarketDataTransport",
    "MarketDataBatch",
    "MarketDataCache",
    "MarketDataError",
    "MarketDataFeed",
    "MarketDataProtocolError",
    "MarketDataRequestError",
    "MarketDataTransportError",
    "MarketDataValidationError",
    "MarketSessionClose",
    "Sleeper",
    "StreamDisconnected",
    "StreamError",
    "StreamProtocolError",
    "StreamStaleError",
    "TransportResponse",
    "WebSocketConnection",
    "WebSocketConnector",
    "WebsocketsConnection",
    "WebsocketsConnector",
    "align_daily_bars_to_session_closes",
    "latest_completed_session",
    "session_closes",
    "session_sequence",
    "validate_bar_batch",
]
